// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcdpAUhlaqPV4a97u94CR7b96yvaH-0AU',
    appId: '1:182949597561:web:bab8d76eecd616d134dfa8',
    messagingSenderId: '182949597561',
    projectId: 'flutterfirebase-b7fec',
    authDomain: 'flutterfirebase-b7fec.firebaseapp.com',
    storageBucket: 'flutterfirebase-b7fec.appspot.com',
    measurementId: 'G-XFX53PD7DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEgTju4kEEOPebihNR_NGhlJt50EdLt0M',
    appId: '1:182949597561:android:2c61ccafb0ca9bf134dfa8',
    messagingSenderId: '182949597561',
    projectId: 'flutterfirebase-b7fec',
    storageBucket: 'flutterfirebase-b7fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEKZO78WZc3lps0s_L844wzSENhcN-e-8',
    appId: '1:182949597561:ios:289742a3672a704334dfa8',
    messagingSenderId: '182949597561',
    projectId: 'flutterfirebase-b7fec',
    storageBucket: 'flutterfirebase-b7fec.appspot.com',
    iosClientId: '182949597561-v0i4ejg25vd0m52765lq7nhp3q6u5h67.apps.googleusercontent.com',
    iosBundleId: 'ldflutterfirebase.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEKZO78WZc3lps0s_L844wzSENhcN-e-8',
    appId: '1:182949597561:ios:289742a3672a704334dfa8',
    messagingSenderId: '182949597561',
    projectId: 'flutterfirebase-b7fec',
    storageBucket: 'flutterfirebase-b7fec.appspot.com',
    iosClientId: '182949597561-v0i4ejg25vd0m52765lq7nhp3q6u5h67.apps.googleusercontent.com',
    iosBundleId: 'ldflutterfirebase.flutterFirebase',
  );
}
